from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Any
import unicodedata

from assess_mc_complexity import assessment_hash, load_assessment
from common import (
    SCHEMA_VERSION,
    VERSION,
    ass_timestamp,
    canonical_hash,
    console_version,
    event_source_text,
    load_events,
    load_manifest,
    manifest_section_contract,
    normalize_mc_punctuation,
    package_input_hash,
    package_manifest_mismatches,
    read_json,
    reject_review_placeholder,
    section_directory,
    utc_now,
    validate_filename_component,
    write_text,
    write_json,
)
from song_progress import progress_ass_path, render_song_progress_ass

ASS_CHINESE_FONT_SIZE = 80
ASS_JAPANESE_FONT_SIZE = 57
ASS_SAFE_TEXT_WIDTH = 1700.0
ASS_MIN_HORIZONTAL_SCALE = 50


def _ass_escape(text: str) -> str:
    return (
        text.replace("\\", "＼")
        .replace("{", "｛")
        .replace("}", "｝")
        .replace("\r\n", r"\N")
        .replace("\r", r"\N")
        .replace("\n", r"\N")
    )


def _estimated_text_width(text: str, font_size: int) -> float:
    widths = []
    for line in str(text).replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        units = sum(
            2 if unicodedata.east_asian_width(character) in {"W", "F", "A"} else 1
            for character in line
        )
        widths.append(units * font_size / 2)
    return max(widths, default=0.0)


def _fitted_horizontal_scale(text: str, font_size: int) -> int:
    width = _estimated_text_width(text, font_size)
    if width <= ASS_SAFE_TEXT_WIDTH:
        return 100
    return max(
        ASS_MIN_HORIZONTAL_SCALE,
        min(100, int(math.floor(ASS_SAFE_TEXT_WIDTH / width * 100))),
    )


def _styled_ass_text(event: dict[str, Any]) -> str:
    source_text = event_source_text(event).strip()
    translation_text = str(event.get("translation", "") or "").strip()
    reject_review_placeholder(source_text)
    reject_review_placeholder(translation_text)
    if event.get("section_type") == "mc":
        source_text = normalize_mc_punctuation(source_text)
        translation_text = normalize_mc_punctuation(translation_text)
    source = _ass_escape(source_text)
    source_scale = _fitted_horizontal_scale(
        source_text,
        ASS_JAPANESE_FONT_SIZE,
    )
    source_line = (
        rf"{{\fs{ASS_JAPANESE_FONT_SIZE}\fscx{source_scale}"
        r"\c&H00FFFFFF&}"
        + source
    )
    if not translation_text:
        return source_line
    translation = _ass_escape(translation_text)
    translation_scale = _fitted_horizontal_scale(
        translation_text,
        ASS_CHINESE_FONT_SIZE,
    )
    translation_line = (
        rf"{{\fs{ASS_CHINESE_FONT_SIZE}\fscx{translation_scale}"
        r"\c&H007AD7FF&}"
        + translation
    )
    return translation_line + r"\N" + source_line


def render_ass(events: list[dict[str, Any]], title: str) -> str:
    header = f"""[Script Info]
; Generated by concert-subtitle v{VERSION}
Title: {title} - concert-subtitle v{VERSION}
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Bilingual,Arial,57,&H00FFFFFF,&H0000FFFF,&H00101010,&H80000000,0,0,0,0,100,100,0,0,1,3,1,2,80,80,58,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    dialogue = []
    for event in events:
        text = _styled_ass_text(event)
        dialogue.append(
            "Dialogue: 0,"
            f"{ass_timestamp(float(event['start']))},"
            f"{ass_timestamp(float(event['end']))},"
            f"Bilingual,{event.get('section_id', '')},0,0,0,,{text}"
        )
    return header + "\n".join(dialogue) + "\n"


def collect_absolute_events(
    concert_dir: Path,
    require_approved: bool = True,
) -> tuple[dict[str, Any], list[dict[str, Any]], list[dict[str, Any]]]:
    concert_dir = concert_dir.resolve()
    manifest = load_manifest(concert_dir)
    validate_filename_component(manifest["concert_id"], "concert_id")
    all_events: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []

    for section_index, section in enumerate(manifest["sections"]):
        section_dir = section_directory(concert_dir, section["id"])
        status_path = section_dir / "status.json"
        status = read_json(status_path) if status_path.is_file() else {}
        package_path = section_dir / "input.json"
        package = read_json(package_path) if package_path.is_file() else {}
        decision_path = section_dir / "review_decision.json"
        decision = read_json(decision_path) if decision_path.is_file() else {}
        gate_path = section_dir / "gate_report.json"
        gate = read_json(gate_path) if gate_path.is_file() else {}
        expected_manifest_hash = canonical_hash(
            manifest_section_contract(manifest, section_index)
        )

        if (
            package.get("input_hash") != package_input_hash(package)
            or package.get("manifest_section_hash") != expected_manifest_hash
            or package_manifest_mismatches(package, manifest, section_index)
        ):
            failures.append(
                {
                    "code": "manifest_changed_after_package",
                    "section_id": section["id"],
                }
            )
            continue

        if require_approved and status.get("status") != "approved":
            failures.append(
                {
                    "code": "section_not_approved",
                    "section_id": section["id"],
                    "status": status.get("status", "missing"),
                }
            )
            continue
        if require_approved and (
            decision.get("decision") != "approved"
            or decision.get("input_hash") != package.get("input_hash")
        ):
            failures.append(
                {
                    "code": "invalid_review_decision",
                    "section_id": section["id"],
                }
            )
            continue
        if require_approved and package.get("section_type") == "mc":
            current_mc_complexity_hash = assessment_hash(
                load_assessment(section_dir)
            )
            if (
                current_mc_complexity_hash is None
                or gate.get("mc_complexity_hash")
                != current_mc_complexity_hash
                or decision.get("mc_complexity_hash")
                != current_mc_complexity_hash
            ):
                failures.append(
                    {
                        "code": "mc_complexity_changed_after_approval",
                        "section_id": section["id"],
                    }
                )
                continue

        events_path = section_dir / "events.json"
        if not events_path.is_file():
            failures.append(
                {"code": "missing_events", "section_id": section["id"]}
            )
            continue
        section_events = load_events(events_path)
        report_path = section_dir / "report.json"
        section_report = read_json(report_path) if report_path.is_file() else {}
        result_hash = canonical_hash(
            {"events": section_events, "report": section_report}
        )
        if require_approved and (
            gate.get("automatic_result") != "passed"
            or gate.get("input_hash") != package.get("input_hash")
            or gate.get("result_hash") != result_hash
            or decision.get("result_hash") != result_hash
        ):
            failures.append(
                {
                    "code": "result_changed_after_approval",
                    "section_id": section["id"],
                }
            )
            continue

        section_duration = float(section["end"]) - float(section["start"])
        for event in section_events:
            relative_start = float(event["start"])
            relative_end = float(event["end"])
            if relative_start < -0.001 or relative_end > section_duration + 0.001:
                failures.append(
                    {
                        "code": "event_outside_section",
                        "section_id": section["id"],
                        "event_id": event.get("id"),
                    }
                )
                continue
            all_events.append(
                {
                    **event,
                    "section_id": section["id"],
                    "section_type": section["type"],
                    "section_order": section["order"],
                    "start": relative_start + float(section["start"]),
                    "end": relative_end + float(section["start"]),
                }
            )

    all_events.sort(key=lambda event: (float(event["start"]), int(event["section_order"])))
    for previous, current in zip(all_events, all_events[1:]):
        overlap = float(previous["end"]) - float(current["start"])
        if overlap > 0.001:
            failures.append(
                {
                    "code": "global_overlap",
                    "previous_event": previous.get("id"),
                    "current_event": current.get("id"),
                    "overlap_seconds": overlap,
                }
            )
    return manifest, all_events, failures


def merge_concert(concert_dir: Path) -> dict[str, Any]:
    concert_dir = concert_dir.resolve()
    manifest, events, failures = collect_absolute_events(concert_dir, True)
    if failures:
        failure_report = {
            "schema_version": SCHEMA_VERSION,
            "tool_version": VERSION,
            "concert_id": manifest["concert_id"],
            "created_at": utc_now(),
            "result": "failed",
            "failures": failures,
        }
        write_json(concert_dir / "run" / "merge_failed_report.json", failure_report)
        raise ValueError(f"全场合并gate失败，共{len(failures)}项")
    progress_ass_text = render_song_progress_ass(manifest)

    output_dir = concert_dir / "output"
    output_dir.mkdir(parents=True, exist_ok=True)
    evidence_dir = concert_dir / "run" / "evidence"
    evidence_dir.mkdir(parents=True, exist_ok=True)
    base_name = manifest["concert_id"]
    ass_path = output_dir / f"{base_name}.ass"
    events_path = evidence_dir / f"{base_name}.merged.events.json"
    report_path = evidence_dir / f"{base_name}.merge.report.json"
    progress_path = progress_ass_path(concert_dir, manifest)

    write_text(
        ass_path,
        render_ass(events, manifest["concert_id"]),
        encoding="utf-8-sig",
        newline="\n",
    )
    write_text(
        progress_path,
        progress_ass_text,
        encoding="utf-8",
        newline="\r\n",
    )
    write_json(
        events_path,
        {
            "schema_version": SCHEMA_VERSION,
            "tool_version": VERSION,
            "concert_id": manifest["concert_id"],
            "events": events,
        },
    )
    report = {
        "schema_version": SCHEMA_VERSION,
        "tool_version": VERSION,
        "concert_id": manifest["concert_id"],
        "created_at": utc_now(),
        "result": "passed",
        "section_count": len(manifest["sections"]),
        "event_count": len(events),
        "overlap_count": 0,
        "outputs": {
            "ass": str(ass_path),
            "song_progress_ass": str(progress_path),
        },
        "evidence": {
            "events": str(events_path),
            "report": str(report_path),
        },
    }
    write_json(report_path, report)
    for legacy_path in (
        output_dir / f"{base_name}.srt",
        output_dir / f"{base_name}.events.json",
        output_dir / f"{base_name}.report.json",
    ):
        legacy_path.unlink(missing_ok=True)
    return report


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="合并全部已批准分段")
    parser.add_argument("--concert-dir", required=True, type=Path)
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    console_version("merge_concert_subtitles")
    report = merge_concert(args.concert_dir)
    print(f"sections={report['section_count']}")
    print(f"events={report['event_count']}")
    print(f"ass={report['outputs']['ass']}")
    print(f"song_progress_ass={report['outputs']['song_progress_ass']}")
    print(f"evidence={report['evidence']['report']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
