from __future__ import annotations

import argparse
import math
import subprocess
from pathlib import Path
from typing import Any

from common import (
    VERSION,
    ass_timestamp,
    canonical_hash,
    console_version,
    load_manifest,
    resolve_binary,
    resolve_review_media,
    validate_filename_component,
    write_text,
)


PLAY_RES_X = 1920
PLAY_RES_Y = 1080
BAR_X = 80
BAR_Y = 62
BAR_WIDTH = 760
BAR_HEIGHT = 6
BAR_GAP = 4
TITLE_SECONDS = 7.0
PROGRESS_SUFFIX = "song-progress.ass"


def song_sections(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    songs = [
        section
        for section in manifest.get("sections", [])
        if section.get("type") == "song"
    ]
    if not songs:
        raise ValueError("Manifest中没有歌曲分段")
    if len(songs) > 80:
        raise ValueError("歌曲数量超过80，细进度条无法保持可辨识分段")
    previous_end = -math.inf
    for index, song in enumerate(songs, start=1):
        start = float(song["start"])
        end = float(song["end"])
        if not math.isfinite(start) or not math.isfinite(end) or end <= start:
            raise ValueError(f"第{index}首歌曲区间非法")
        if start < previous_end - 0.001:
            raise ValueError("歌曲分段存在时间重叠")
        if not str(song.get("title", "")).strip():
            raise ValueError(f"第{index}首歌曲缺少歌名")
        previous_end = end
    return songs


def segment_bounds(total: int, *, x: int = BAR_X, width: int = BAR_WIDTH) -> list[tuple[int, int]]:
    if total <= 0:
        raise ValueError("歌曲数量必须大于0")
    gap = BAR_GAP if total <= 30 else 2
    available = width - gap * (total - 1)
    if available < total * 4:
        raise ValueError("歌曲数量过多，进度条分段宽度不足")
    base_width, remainder = divmod(available, total)
    bounds = []
    cursor = x
    for index in range(total):
        width = base_width + (1 if index < remainder else 0)
        bounds.append((cursor, cursor + width))
        cursor += width + gap
    return bounds


def _ass_escape(value: str) -> str:
    return (
        value.replace("\\", r"\\")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _rectangle(x0: int, y0: int, x1: int, y1: int) -> str:
    return f"m {x0} {y0} l {x1} {y0} {x1} {y1} {x0} {y1}"


def _dialogue(
    layer: int,
    start: float,
    end: float,
    style: str,
    text: str,
) -> str:
    return (
        f"Dialogue: {layer},{ass_timestamp(start)},{ass_timestamp(end)},"
        f"{style},,0,0,0,,{text}"
    )


def render_song_progress_ass(manifest: dict[str, Any]) -> str:
    songs = song_sections(manifest)
    presentation = manifest.get("presentation", {})
    bar = {"x": BAR_X, "y": BAR_Y, "width": BAR_WIDTH, "height": BAR_HEIGHT}
    bar.update(presentation.get("progress_bar", {}))
    if any(type(bar[key]) is not int for key in ("x", "y", "width", "height")) or not (
        0 <= bar["x"] < PLAY_RES_X and 0 <= bar["y"] < PLAY_RES_Y
        and 0 < bar["width"] <= PLAY_RES_X - bar["x"]
        and 0 < bar["height"] <= PLAY_RES_Y - bar["y"]
    ):
        raise ValueError("progress_bar必须使用1920×1080画面内的整数坐标和正尺寸")
    bounds = segment_bounds(len(songs), x=bar["x"], width=bar["width"])
    bar_y, bar_height = bar["y"], bar["height"]
    manifest_hash = canonical_hash(manifest)
    header = f"""[Script Info]
; Generated by concert-subtitle v{VERSION}
; Manifest-SHA256: {manifest_hash}
Title: {manifest.get('concert_id', 'concert')} song progress
ScriptType: v4.00+
PlayResX: {PLAY_RES_X}
PlayResY: {PLAY_RES_Y}
WrapStyle: 2
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: ProgressTitle,Yu Gothic UI,46,&H00FFFFFF,&H00FFFFFF,&H00101010,&H78000000,-1,0,0,0,100,100,0,0,1,2,1,7,80,80,92,1
Style: ProgressArtist,Yu Gothic UI,28,&H30FFFFFF,&H30FFFFFF,&H00101010,&H78000000,0,0,0,0,100,100,0,0,1,1.5,1,7,80,80,148,1
Style: ProgressDrawing,Arial,20,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    dialogue: list[str] = []
    base_shape = " ".join(
        _rectangle(x0, bar_y, x1, bar_y + bar_height)
        for x0, x1 in bounds
    )
    for song_index, song in enumerate(songs):
        start = float(song["start"])
        end = float(song["end"])
        duration_ms = max(1, int(round((end - start) * 1000)))
        dialogue.append(
            _dialogue(
                10,
                start,
                end,
                "ProgressDrawing",
                (
                    r"{\an7\pos(0,0)\p1\bord0\shad0"
                    r"\1c&H00FFFFFF&\alpha&HAA&}"
                    + base_shape
                ),
            )
        )
        if song_index:
            completed_shape = " ".join(
                _rectangle(x0, bar_y, x1, bar_y + bar_height)
                for x0, x1 in bounds[:song_index]
            )
            dialogue.append(
                _dialogue(
                    11,
                    start,
                    end,
                    "ProgressDrawing",
                    (
                        r"{\an7\pos(0,0)\p1\bord0\shad0"
                        r"\1c&H005DC9F4&\alpha&H45&}"
                        + completed_shape
                    ),
                )
            )
        current_start, current_end = bounds[song_index]
        current_width = current_end - current_start
        dialogue.append(
            _dialogue(
                12,
                start,
                end,
                "ProgressDrawing",
                (
                    "{\\an7"
                    f"\\pos({current_start},{bar_y})"
                    r"\p1\bord0\shad0\1c&H005DC9F4&\alpha&H00&"
                    "\\fscx0\\fscy100"
                    f"\\t(0,{duration_ms},1,\\fscx100)"
                    "}"
                    f"m 0 0 l {current_width} 0 {current_width} "
                    f"{bar_height} 0 {bar_height}"
                ),
            )
        )
        if song.get("source_song_title", presentation.get("source_song_titles", False)):
            continue
        title_end = min(end, start + TITLE_SECONDS)
        fade_out = min(500, max(100, int((title_end - start) * 250)))
        title = _ass_escape(str(song.get("title", "")).strip())
        dialogue.append(
            _dialogue(
                20,
                start,
                title_end,
                "ProgressTitle",
                f"{{\\fad(250,{fade_out})}}{title}",
            )
        )
        artist = _ass_escape(str(song.get("artist", "")).strip())
        if artist:
            dialogue.append(
                _dialogue(
                    20,
                    start,
                    title_end,
                    "ProgressArtist",
                    f"{{\\fad(250,{fade_out})}}{artist}",
                )
            )
    return header + "\n".join(dialogue) + "\n"


def progress_ass_path(concert_dir: Path, manifest: dict[str, Any]) -> Path:
    concert_id = validate_filename_component(
        str(manifest["concert_id"]),
        "concert_id",
    )
    return concert_dir / "run" / "evidence" / f"{concert_id}.{PROGRESS_SUFFIX}"


def write_song_progress_ass(concert_dir: Path) -> Path:
    concert_dir = concert_dir.resolve()
    manifest = load_manifest(concert_dir)
    output_path = progress_ass_path(concert_dir, manifest)
    write_text(
        output_path,
        render_song_progress_ass(manifest),
        encoding="utf-8",
        newline="\r\n",
    )
    return output_path


def song_progress_ass_failures(
    manifest: dict[str, Any],
    actual: str | None,
) -> list[str]:
    if actual is None:
        return ["missing_song_progress_ass"]
    expected = render_song_progress_ass(manifest)
    if actual.replace("\r\n", "\n") != expected:
        return ["song_progress_ass_stale_or_modified"]
    return []


def validate_song_progress_ass(concert_dir: Path) -> list[str]:
    concert_dir = concert_dir.resolve()
    manifest = load_manifest(concert_dir)
    output_path = progress_ass_path(concert_dir, manifest)
    if not output_path.is_file():
        return song_progress_ass_failures(manifest, None)
    try:
        actual = output_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return ["song_progress_ass_not_utf8"]
    return song_progress_ass_failures(manifest, actual)


def _filter_path(path: Path) -> str:
    value = path.resolve().as_posix()
    return value.replace(":", r"\:").replace("'", r"\'")


def _video_inputs(
    concert_dir: Path,
    *,
    review: bool = False,
) -> tuple[dict[str, Any], Path, Path, Path]:
    from merge_concert_subtitles import collect_absolute_events, render_ass

    manifest, events, failures = collect_absolute_events(concert_dir, True)
    if failures:
        codes = ",".join(str(item.get("code", "unknown")) for item in failures)
        raise ValueError("全场合并gate失败：" + codes)
    source = (
        resolve_review_media(manifest, concert_dir)
        if review
        else Path(manifest["source_media"]).resolve()
    )
    caption_ass = concert_dir / "output" / f"{manifest['concert_id']}.ass"
    progress_ass = progress_ass_path(concert_dir, manifest)
    if not source.is_file():
        raise FileNotFoundError(f"源视频不存在：{source}")
    if not caption_ass.is_file():
        raise FileNotFoundError(f"正式字幕ASS不存在：{caption_ass}")
    caption_text = caption_ass.read_text(encoding="utf-8-sig")
    if caption_text.replace("\r\n", "\n") != render_ass(
        events,
        manifest["concert_id"],
    ):
        raise ValueError("正式字幕ASS与当前已批准事件不一致")
    failures = validate_song_progress_ass(concert_dir)
    if failures:
        raise ValueError("进度图形层校验失败：" + ",".join(failures))
    return manifest, source, caption_ass, progress_ass


def _subtitle_filter(caption_ass: Path, progress_ass: Path) -> str:
    return (
        f"subtitles=filename='{_filter_path(caption_ass)}',"
        f"subtitles=filename='{_filter_path(progress_ass)}'"
    )


def render_final_video(
    concert_dir: Path,
    output_path: Path | None = None,
    ffmpeg_value: str | None = None,
    crf: int = 18,
    preset: str = "medium",
) -> Path:
    concert_dir = concert_dir.resolve()
    manifest, source, caption_ass, progress_ass = _video_inputs(concert_dir)
    ffmpeg = resolve_binary("ffmpeg", ffmpeg_value)
    destination = (
        output_path.resolve()
        if output_path
        else concert_dir / "output" / f"{manifest['concert_id']}.hardsub.mp4"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    command = [
        str(ffmpeg),
        "-nostdin",
        "-hide_banner",
        "-loglevel",
        "error",
        "-y",
        "-i",
        str(source),
        "-map",
        "0:v:0",
        "-map",
        "0:a:0?",
        "-vf",
        _subtitle_filter(caption_ass, progress_ass),
        "-c:v",
        "libx264",
        "-preset",
        preset,
        "-crf",
        str(crf),
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-b:a",
        "192k",
        "-movflags",
        "+faststart",
        str(destination),
    ]
    subprocess.run(command, check=True)
    return destination


def review_windows(manifest: dict[str, Any], concert_dir: Path | None = None) -> list[tuple[float, float]]:
    windows: list[tuple[float, float]] = []
    for song in song_sections(manifest):
        start = float(song["start"])
        end = float(song["end"])
        duration = end - start
        candidates = [
            (start, min(end, start + 4.0)),
            (
                max(start, start + duration / 2 - 0.75),
                min(end, start + duration / 2 + 0.75),
            ),
            (max(start, end - 2.0), end),
        ]
        for candidate_start, candidate_end in candidates:
            if candidate_end - candidate_start >= 0.2:
                windows.append((candidate_start, candidate_end))
    merged: list[tuple[float, float]] = []
    for start, end in windows:
        if merged and start <= merged[-1][1] + 0.01:
            merged[-1] = (merged[-1][0], max(merged[-1][1], end))
        else:
            merged.append((start, end))
    return merged


def merge_review_ass(caption_text: str, progress_text: str) -> str:
    caption_lines = caption_text.replace("\r\n", "\n").splitlines()
    progress_lines = progress_text.replace("\r\n", "\n").splitlines()
    try:
        events_index = caption_lines.index("[Events]")
    except ValueError as error:
        raise ValueError("正式字幕ASS缺少[Events]") from error
    existing_styles = {
        line.split(",", 1)[0]
        for line in caption_lines
        if line.startswith("Style:")
    }
    progress_styles = [
        line
        for line in progress_lines
        if line.startswith("Style:") and line.split(",", 1)[0] not in existing_styles
    ]
    progress_events = [
        line for line in progress_lines if line.startswith("Dialogue:")
    ]
    merged = (
        caption_lines[:events_index]
        + progress_styles
        + caption_lines[events_index:]
        + progress_events
    )
    return "\n".join(merged).rstrip() + "\n"


def write_review_ass(
    concert_dir: Path,
    output_path: Path | None = None,
) -> Path:
    concert_dir = concert_dir.resolve()
    manifest, source, caption_ass, progress_ass = _video_inputs(
        concert_dir,
        review=True,
    )
    windows = review_windows(manifest, concert_dir)
    destination = (
        output_path.resolve()
        if output_path
        else concert_dir / "run" / "review" / "song-progress-review.ass"
    )
    if destination.suffix.lower() != ".ass":
        raise ValueError("进度预览只输出单一外挂ASS")
    destination.parent.mkdir(parents=True, exist_ok=True)
    write_text(
        destination,
        merge_review_ass(
            caption_ass.read_text(encoding="utf-8-sig"),
            progress_ass.read_text(encoding="utf-8-sig"),
        ),
        encoding="utf-8-sig",
        newline="\n",
    )
    windows_path = destination.with_name(f"{destination.stem}-windows.tsv")
    rows = ["index\tstart\tend\tsource\tsubtitle"]
    rows.extend(
        f"{index}\t{start:.3f}\t{end:.3f}\t{source}\t{destination}"
        for index, (start, end) in enumerate(windows, start=1)
    )
    write_text(windows_path, "\n".join(rows) + "\n", encoding="utf-8", newline="\n")
    return destination


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="生成并烧录演唱会歌曲细进度条")
    subparsers = parser.add_subparsers(dest="action", required=True)
    for action in ("build", "validate", "render", "review"):
        action_parser = subparsers.add_parser(action)
        action_parser.add_argument("--concert-dir", required=True, type=Path)
        if action in {"render", "review"}:
            action_parser.add_argument("--output", type=Path)
        if action == "render":
            action_parser.add_argument("--ffmpeg")
            action_parser.add_argument("--crf", type=int, default=18)
            action_parser.add_argument("--preset", default="medium")
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    console_version("song_progress")
    if args.action == "build":
        print(f"ass={write_song_progress_ass(args.concert_dir)}")
        return 0
    if args.action == "validate":
        failures = validate_song_progress_ass(args.concert_dir)
        print(f"result={'failed' if failures else 'passed'}")
        for failure in failures:
            print(f"failure={failure}")
        return 2 if failures else 0
    if args.action == "render":
        output = render_final_video(
            args.concert_dir,
            args.output,
            args.ffmpeg,
            args.crf,
            args.preset,
        )
        print(f"video={output}")
        return 0
    output = write_review_ass(
        args.concert_dir,
        args.output,
    )
    print(f"review_ass={output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
